feat: add beancount hash tag support
deb-sig/double-entry-generator pull request #67
Opened 2022-09-23 05:10 UTC by p3psi-boo

支持 Beancount 的 [Hashtag](https://beancount.github.io/docs/beancount_language_syntax.html#tags)，目前仅实现了支付宝以及微信

用法：
在规则添加 `tags` 字段，多个 tag 之间用 `seq`（默认为`,`）进行分隔。

2022-09-23 10:15 UTC, Triple-Z commented
Good feature :) but I prefer to use the metadata :P

2022-09-26 03:25 UTC, p3psi-boo commented
我这边的账单不全是生成的，有时候会自己手动录入一些数据，特别是一段时间的账单，用 `pushtag` 和 `poptag` 比较方便，然后这样子可以和生成的一起查询。

因此如果有类似我这种使用场景的，可以用 tag 来标记。

代码可能不太好，第一次写 Golang，望请多多包涵。

2022-10-01 04:59 UTC, Triple-Z approved these changes
LGTM

2022-10-01 15:23 UTC, gaocegege commented
Thanks for your contribution! :tada: :+1:

Please help fix the test cases.

2022-10-10 00:58 UTC, p3psi-boo commented
Fixed

2022-10-10 01:34 UTC, gaocegege commented
LGTM

/cc @Triple-Z 

Let's merge it.

2022-10-10 01:34 UTC, gaocegege commented
Thanks for your contribution! :tada: :+1:

2022-10-10 02:05 UTC, Triple-Z requested changes
Mostly fine, please look at the transaction template.

2022-10-10 02:05 UTC, Triple-Z commented on pkg/compiler/beancount/template.go
> +var normalOrder = `{{ .PayTime.Format "2006-01-02" }} * "{{ EscapeString .Peer }}" "{{ EscapeString .Item }}" {{ range .Tags }}#{{ . }} {{ end }}{{ if .Note }}  ; {{ .Note }}{{ end }}
Tag 的空格应该放在循环内，如 `#` 的前面，而不是放在循环外，这样导致每个没有 tag 的交易末尾都多了一个空格。

2022-10-17 09:26 UTC, p3psi-boo commented on pkg/compiler/beancount/template.go
> +var normalOrder = `{{ .PayTime.Format "2006-01-02" }} * "{{ EscapeString .Peer }}" "{{ EscapeString .Item }}" {{ range .Tags }}#{{ . }} {{ end }}{{ if .Note }}  ; {{ .Note }}{{ end }}
感谢，已更新

2022-10-17 17:35 UTC, Triple-Z requested changes
请修复测试。

2022-10-17 17:35 UTC, Triple-Z commented on example/alipay/example-alipay-output.beancount
> +2020-06-02 * "蚂蚁财富-蚂蚁（杭州）基金销售有限公司" "蚂蚁财富-ABCD-卖出至余额宝"
不应该多一个空格，需要看下模版的问题。

2022-10-17 17:35 UTC, Triple-Z commented on example/wechat/example-wechat-output.beancount
> +2017-10-20 * "建设银行信用卡还款" "/"
同理，不应该结尾多一个空格。

2022-10-18 03:32 UTC, Triple-Z commented on README.md
> +在单条规则中可以使用 `tags` 来设置流水的 [Tag](https://beancount.github.io/docs/beancount_language_syntax.html#tags)，使用 `sep` 作为分隔符。
目前配置上的 key 都是单数形式，建议标签也使用单数形式 `tag`  ，WDYT @p3psi-boo @gaocegege

2022-10-18 03:38 UTC, gaocegege commented on README.md
> +在单条规则中可以使用 `tags` 来设置流水的 [Tag](https://beancount.github.io/docs/beancount_language_syntax.html#tags)，使用 `sep` 作为分隔符。
LGTM

2022-11-01 13:20 UTC, Triple-Z commented on README.md
> +在单条规则中可以使用 `tags` 来设置流水的 [Tag](https://beancount.github.io/docs/beancount_language_syntax.html#tags)，使用 `sep` 作为分隔符。
I have fixed this.

2022-11-01 13:21 UTC, Triple-Z approved these changes
LGTM

2022-11-01 13:22 UTC, merged