fix(alipay): refund transactions with txType as "收入"
deb-sig/double-entry-generator pull request #83
Opened 2023-01-27 16:25 UTC by wych42

see https://github.com/deb-sig/double-entry-generator/issues/82

2023-01-28 03:14 UTC, Triple-Z requested changes
建议同步在 README 中修改支付宝配置中的增减账户关系表。

2023-01-28 03:14 UTC, Triple-Z commented on example/alipay/example-alipay-output.beancount
> +2021-06-01 * "dettol滴露官方旗舰店" "退款-【直接下单付款】滴露消毒液1.2L*2家用杀菌消毒水衣物地板宠物"
请修复测试。

2023-01-29 13:17 UTC, wych42 commented
> 建议同步在 README 中修改支付宝配置中的增减账户关系表。

README 中的支付宝的增减账户关系表格是正确的，只是在「收支=收入并且是退款交易」时，代码结果与表格中结果不一致。

2023-01-29 13:27 UTC, Triple-Z commented
> README 中的支付宝的增减账户关系表格是正确的，只是在「收支=收入并且是退款交易」时，代码结果与表格中结果不一致。

是的，建议将「收支=收入并且是退款交易」的场景也补充进去。

2023-01-29 13:33 UTC, Triple-Z commented
btw 我这里 diff 看中文大部分都是乱码，貌似是网页编码问题？

<img width="1481" alt="image" src="https://user-images.githubusercontent.com/16285716/215329652-9e8128c9-70cc-4167-b2bf-418cae4ac0ca.png">

2023-01-29 13:42 UTC, wych42 commented
> > README 中的支付宝的增减账户关系表格是正确的，只是在「收支=收入并且是退款交易」时，代码结果与表格中结果不一致。
> 
> 是的，建议将「收支=收入并且是退款交易」的场景也补充进去。

已经补充。同时添加了收/支=其他的退款交易。

2023-01-29 13:42 UTC, Triple-Z approved these changes
LGTM

2023-01-29 13:43 UTC, merged

2023-01-29 13:43 UTC, wych42 commented
> btw 我这里 diff 看中文大部分都是乱码，貌似是网页编码问题？
> 
> <img alt="image" width="1481" src="https://user-images.githubusercontent.com/16285716/215329652-9e8128c9-70cc-4167-b2bf-418cae4ac0ca.png">

我这里看到的刚好和你相反。主要原因我猜测是：

账单文件 example/alipay/example-alipay-records.csv 是 gbk 编码
bean 文件 example/alipay/example-alipay-output.beancount 是 UTF-8 编码

在一个页面展示时，网页错乱了。

2023-01-29 13:43 UTC, Triple-Z commented
Thanks for your contribution 🎉

2023-01-29 13:44 UTC, Triple-Z commented
> 我这里看到的刚好和你相反。

这应该是对的，UTF-8 应该正常显示，GBK 应该异常。不知道我这网页咋了 😆 。